MuhammadShoppingCart/Models/Order.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MuhammadShoppingCart.Models
{
    public class Order
    {
        //Add the necessary properties
        public int Id { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string ZipCode { get; set; }
        public string Country { get; set; }
        public string Phone { get; set; }
        public DateTime OrderDate { get; set; }
        public string CustomerId { get; set; }
        public decimal Total { get; set; }
        public bool Completed { get; set; }

        //Navigation Properties

        //This virtual property is here because Order is the Parent of OrderDetail
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }

        //This virtual property is here because Order is the Child of AspNetUsers
        public virtual ApplicationUser Customer { get; set; }

        public Order()
        {
            //We need one of these lines for each ICollection type property
            this.OrderDetails = new HashSet<OrderDetail>();
        }
    }
}

MuhammadShoppingCart/Controllers/ItemsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MuhammadShoppingCart.Models;
using MuhammadShoppingCart.Helper;
using System.IO;

namespace MuhammadShoppingCart.Controllers
{
    public class ItemsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        private ImageUploadValidator validator = new ImageUploadValidator();

        // GET: Items
        //Returns ALL watches
        //[Authorize]
        public ActionResult Index()
        {
            return View(db.Items.ToList());
        }

        //Returns Mens watches
        //[Authorize]
        public ActionResult MensIndex()
        {
            //Additional "Where" clause has been added in to limit the set of data coming in
            return View("Index", db.Items.Where(w => w.Gender == "M").ToList());
        }

        //Returns Womens watches
        //[Authorize]
        public ActionResult WomensIndex()
        {
            return View("Index", db.Items.Where(w => w.Gender == "W").ToList());
        }

        //Returns Womens watches
        //[Authorize]
        public ActionResult SportsIndex()
        {
            return View("Index", db.Items.Where(w => w.Gender == "S").ToList());
        }

        public ActionResult CheapestIndex()
        {
            return View("Index", db.Items.Where(p => p.Price < 250).ToList());
        }

        public ActionResult CheaperIndex()
        {
            return View("Index", db.Items.Where(p => p.Price >= 250 && p.Price < 1000).ToList());
        }

        public ActionResult CheapIndex()
        {
            return View("Index", db.Items.Where(p => p.Price >= 1000 && p.Price < 5000).ToList());
        }

        public ActionResult ExpensiveIndex()
        {
            return View("Index", db.Items.Where(p => p.Price >= 5000).ToList());
        }


        // GET: Items/Details/5
        //[Authorize (Roles = "Admin")]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            //We're setting this item object that is an instance of item and giving it a value of a database
            Item item = db.Items.Find(id);
            if (item == null)
            {
                return HttpNotFound();
            }
            return View(item);
        }

        // GET: Items/Create
        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            //The following line returns the "Create" View
            return View();
        }

        // POST: Items/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.

        //These square bracket things are called a data annotation, the [HttpPost] allows this "Create" to be of the "Post" variety. Without it, it's assumed that it's an HttpGet
        [HttpPost]
        [ValidateAntiForgeryToken] //Another security measure 
        public ActionResult Create([Bind(Include = "Name,Price,MediaUrl,Description,Gender")] Item item, HttpPostedFileBase Image)
        {
            if (ModelState.IsValid)
            {
                ImageUploadValidator validator = new ImageUploadValidator();
                    if (ImageUploadValidator.IsWebFriendlyImage(Image))
                    {
                        var fileName = Path.GetFileName(Image.FileName);
                        Image.SaveAs(Path.Combine(Server.MapPath("~/images/uploads/"), fileName));
                        item.MediaUrl = "~/images/uploads/" + fileName;
                    }
                    item.Created = DateTime.Now;
                    //Attaches this particular item to the db set (db is an instance of ApplicationDbContext), the next one stores it back to SQL.
                    db.Items.Add(item);
                    db.SaveChanges();
                    return RedirectToAction("Index");
            }

            return View(item);
        }

        // GET: Items/Edit/5
        //[Authorize (Roles = "Admin")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            //Going out to the items table in the database finding id and assigning it to item. 
            Item item = db.Items.Find(id);
            if (item == null)
            {
                return HttpNotFound();
            }
            return View(item);
        }

        // POST: Items/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        //[Authorize(Roles = "Admin")]
        public ActionResult Edit([Bind(Include = "Id,Name,Price,MediaUrl,Description,Created,Updated")] Item item)
        {
            if (ModelState.IsValid)
            {
                db.Entry(item).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(item);
        }

        // GET: Items/Delete/5
        //[Authorize(Roles = "Admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Item item = db.Items.Find(id);
            if (item == null)
            {
                return HttpNotFound();
            }
            return View(item);
        }

        // POST: Items/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Item item = db.Items.Find(id);
            db.Items.Remove(item);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        //Here we're going out and doing some garbage collection and reclaim lost memory. This is done automatically whenever it can
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MuhammadShoppingCart/Controllers/OrdersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MuhammadShoppingCart.Models;
using Microsoft.AspNet.Identity;

namespace MuhammadShoppingCart.Controllers
{
    public class OrdersController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Orders
        public ActionResult Index()
        {
            //You are going out and getting the Orders table, and including information about the customer. You can only do this b/v of the Customer navigation property in the Order model.
            //var orders = db.Orders.Include(o => o.Customer);
            var userId = User.Identity.GetUserId();
            var orderHistory = new List<Order>();

            if (userId == null)
            {
                orderHistory = db.Orders.ToList();
            }
            else
            {
                orderHistory = db.Orders.Where(o => o.CustomerId == userId).ToList();
            }
            return View(orderHistory);
        }
        // GET: Orders
        public ActionResult Complete(int? id)
        {
            if(id != null)
            {
                //"You must be loggen in, & I'm gonna grab the id of whoever's logged in & assign that to the variable userid
                var userid = User.Identity.GetUserId();

                var completeOrder = db.Orders.Find(id);

                //Here we're using the Navigation property of OrderDetails to get a reference to this Orders details. See Models > Order > Line 26
                var orderdetail = completeOrder.OrderDetails.ToList();

                //Going out to ShoppingCart table & locating the record who's CustomerId is equal to userId, using Where clause. Then assign value to shoppingcarts
                //"s" in the lambda statement is referring to the shoppingcarts table. reads like: "s goes to s.CustomerId equals userid"
                var shoppingcarts = db.ShoppingCarts.Where(s => s.CustomerId == userid);

                //Now that we completed the Order we need to clear out the ShoppingCart
                if (shoppingcarts != null)
                {
                    //Cycle through each ShoppingCart record in the ShoppingCarts list
                    foreach (var shopping in shoppingcarts)
                    {
                        db.ShoppingCarts.Remove(shopping);
                    }
                }

                //Saves both Orders and ShoppingCart changes back to db (notice how we only need one for both statements)
                db.SaveChanges();
            }

            //Jason wouldn't do this, he'd probably return to some kind of receipt page. or return View("OrderConfirm");
            return View();
        }

        //GET: OrderConfirm
        public ActionResult OrderConfirm()
        {
            return View();
        }

        // GET: Orders/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Order order = db.Orders.Find(id);
            if (order == null)
            {
                return HttpNotFound();
            }
            return View(order);
        }

        // GET: Orders/Create
        //In order to place an order we really need Address, City etc. information. We are going to use the GET for that
        public ActionResult Create()
        {
            return View();
        }

        // POST: Orders/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        //Method declaration returning a type ActionResult, 
        public ActionResult Create([Bind(Include = "Address,City,State,ZipCode,Country,Phone")] Order order)
        {
            //Go out to database, users table, and find record that has this id, but return the whole record & set it equal to user
            var user = db.Users.Find(User.Identity.GetUserId());

            //Grab the records where CustomerId is equal to user.Id
            var shoppingcart = db.ShoppingCarts.Where(s => s.CustomerId == user.Id).ToList();

            //variable of type decimal that will cylce through the items in our list
            decimal totalAmt = 0;
            if (shoppingcart.Count != 0)
            {
                if (ModelState.IsValid)
                {
                    foreach (var product in shoppingcart)
                    {
                        OrderDetail orderdetail = new OrderDetail();
                        orderdetail.ItemId = product.ItemId;
                        orderdetail.OrderId = order.Id;
                        orderdetail.Quantity += product.Count;
                        orderdetail.UnitPrice = product.Item.Price;
                        totalAmt += (product.Count * product.Item.Price);

                        db.OrderDetails.Add(orderdetail);
                    }

                    order.Total = totalAmt;
                    order.Completed = true;
                    order.OrderDate = DateTime.Now;
                    order.CustomerId = user.Id;
                    db.Orders.Add(order);
                    db.SaveChanges();

                    //Call the Complete method here to remove all shopping 
                    this.Complete(order.Id);

                    var myOrder = db.Orders.Where(o => o.Id == order.Id).Include("Customer").Single();
                    return View("Receipt", myOrder);
                }
            }
            //ViewBag.CustomerId = new SelectList(db.Users, "Id", "FirstName", order.CustomerId);
            ViewBag.NoItem = "There's no item to order";
            return View(order);
        }

        // GET: Orders/Edit/5
        //Creating an ActionResult called Edit w/ nullable int parameter called id 
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Order order = db.Orders.Find(id);
            if (order == null)
            {
                return HttpNotFound();
            }
            ViewBag.CustomerId = new SelectList(db.Users, "Id", "FirstName", order.CustomerId);
            return View(order);
        }

        // POST: Orders/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Address,City,State,ZipCode,Country,Phone,OrderDate,CustomerId,Total,Completed")] Order order)
        {
            if (ModelState.IsValid)
            {
                db.Entry(order).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CustomerId = new SelectList(db.Users, "Id", "FirstName", order.CustomerId);
            return View(order);
        }

        // GET: Orders/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Order order = db.Orders.Find(id);
            if (order == null)
            {
                return HttpNotFound();
            }
            return View(order);
        }

        // POST: Orders/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Order order = db.Orders.Find(id);
            db.Orders.Remove(order);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MuhammadShoppingCart/Views/Orders/Create.cshtml
@model MuhammadShoppingCart.Models.Order

@{
    ViewBag.Title = "Create";
}

<h2>Submit Order</h2>

<div class="row">
    <div class="col-md-8">
        <section id="loginForm">
            @using (Html.BeginForm("Create", "Orders", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
            {
                @Html.AntiForgeryToken()

                <div class="account-in">
                    <div class="container">
                        <h3>Shipping Information</h3>
                        <div class="col-md-7 account-top">
                            <div>
                                <span>Address</span>
                                <input name="Address" type="text">
                            </div>
                            <div>
                                <span>City</span>
                                <input name="City" type="text">
                            </div>
                            <div>
                                <span>State</span>
                                <input name="State" type="text">
                            </div>
                            <div>
                                <span>Zip Code</span>
                                <input name="ZipCode" type="text">
                            </div>
                            <div>
                                <span>Country</span>
                                <input name="Country" type="text">
                            </div>
                            <div>
                                <span>Phone</span>
                                <input name="Phone" type="text">

                                <div class="clearfix"> </div>

                                <div class="form-group">
                                    <div class="col-md-8">
                                        <input name="template" type="submit" value="Submit">
                                        <a name="template" class="btn btn-default" href=@Url.Action("Index", "ShoppingCart")>Back to Cart</a>
                                    </div>
                                </div>

                            </div>
                        </div>
                    </div>
                </div>
                @* Enable this once you have account confirmation enabled for password reset functionality
                    <p>
                        @Html.ActionLink("Forgot your password?", "ForgotPassword")
                    </p>*@
            }
        </section>
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MuhammadShoppingCart/Views/Orders/Delete.cshtml
@model MuhammadShoppingCart.Models.Order

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Order</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Customer.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Customer.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.City)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.City)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.State)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.State)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ZipCode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ZipCode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Country)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Country)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Phone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Phone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.OrderDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OrderDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Total)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Total)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Completed)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Completed)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

MuhammadShoppingCart/Views/Orders/Details.cshtml
@model MuhammadShoppingCart.Models.Order

@{
    ViewBag.Title = "Details";
}

<h2>Order Summary</h2>
<hr />

<div>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Customer.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Customer.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.City)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.City)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.State)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.State)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ZipCode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ZipCode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Country)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Country)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Phone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Phone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.OrderDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OrderDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Total)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Total)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Completed)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Completed)
        </dd>

    </dl>
</div>

<p>
    @Html.ActionLink("Back to Order History", "Index")
</p>

<hr />

<div>
    <h2>Order Details</h2>
    <div class="account-in">
        <div class="container">
            <div class="check_box">
                <div class="col-md-9 cart-items">
                    @foreach (var detail in Model.OrderDetails)
                    {
                        <div class="cart-header">

                            <div class="cart-sec simpleCart_shelfItem">
                                <div class="cart-item cyc">
                                    <img src="@Url.Content(detail.Item.MediaUrl)" class="img-responsive" alt="" />
                                </div>
                                <div class="cart-item-info">
                                    <h3><a href="#">@detail.Item.Name</a></h3>
                                    <ul class="qty">
                                        <li><p>Description : @detail.Item.Description</p></li>
                                        <li><p>Qty : @detail.Quantity</p></li>
                                    </ul>
                                    <div class="delivery">
                                        <p>Price  : @detail.Item.Price</p>
                                        <div class="clearfix"></div>
                                    </div>
                                </div>
                                <div class="clearfix"></div>
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>

MuhammadShoppingCart/Views/Orders/Index.cshtml
@model IEnumerable<MuhammadShoppingCart.Models.Order>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Customer.FirstName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Address)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.City)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.State)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ZipCode)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Country)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Phone)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.OrderDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Total)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Completed)
        </th>
        <th></th>
    </tr>

@foreach (var order in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => order.Customer.FirstName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => order.Address)
        </td>
        <td>
            @Html.DisplayFor(modelItem => order.City)
        </td>
        <td>
            @Html.DisplayFor(modelItem => order.State)
        </td>
        <td>
            @Html.DisplayFor(modelItem => order.ZipCode)
        </td>
        <td>
            @Html.DisplayFor(modelItem => order.Country)
        </td>
        <td>
            @Html.DisplayFor(modelItem => order.Phone)
        </td>
        <td>
            @Html.DisplayFor(modelItem => order.OrderDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => order.Total)
        </td>
        <td>
            @Html.DisplayFor(modelItem => order.Completed)
        </td>
        <td>
            @Html.ActionLink("Details", "Details", new { id=order.Id }) 
        </td>
    </tr>
}

</table>

MuhammadShoppingCart/Views/Orders/Receipt.cshtml
@model MuhammadShoppingCart.Models.Order

<div class="container">
    <div class="grid_1">
        <br />
        <div class="row">  
            <div class="col-md-1"></div>
            <div class="col-md-4">
                <h1 class="text-left">Receipt</h1>
                <p class="text-left">Thank you for shopping at MMS Watches!</p>
            </div>
            <div class="col-md-7"></div>
        </div>
        <div class="row">  
            <div class="col-md-1"></div>
            <div class="col-md-2">
                <h4 class="text-left">First Name: </h4>
                <h4 class="text-left">Address: </h4>
                <h4 class="phone_desc text-left">City: </h4>
                <h4 class="phone_desc text-left">State: </h4>
                <h4 class="phone_desc text-left">Zip Code: </h4>
                <h4 class="phone_desc text-left">Country: </h4>
            </div>
            <div class="col-md-9">
                <h4 class="text-left">@Html.DisplayFor(model => model.Customer.FirstName)</h4>
                <h4 class="phone_desc text-left">@Html.DisplayFor(model => model.Address)</h4>
                <h4 class="phone_desc text-left">@Html.DisplayFor(model => model.City)</h4>
                <h4 class="phone_desc text-left">@Html.DisplayFor(model => model.State)</h4>
                <h4 class="phone_desc text-left">@Html.DisplayFor(model => model.ZipCode)</h4>
                <h4 class="phone_desc text-left">@Html.DisplayFor(model => model.Country)</h4>
            </div>
        </div>
        <div class="row">
            <div class="col-md-1"></div>
            <div class="col-md-2">
                <h4 class="phone_desc text-left">Phone: </h4>
                <div class="clearfix"> </div>
            </div>
            <div class="col-md-9">
                <h4 class="phone_desc text-left">@Html.DisplayFor(model => model.Phone)</h4>
                <div class="clearfix"> </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-1"></div>
            <div class="col-md-2">
                <h4 class="phone_desc text-left">Order Date: </h4>
                <div class="clearfix"> </div>
                <h4 class="phone_desc text-left">Total: </h4>
                <div class="clearfix"> </div>
            </div>
            <div class="col-md-9">
                <h4 class="phone_desc text-left">@Html.DisplayFor(model => model.OrderDate) </h4>
                <div class="clearfix"> </div>
                <h4 class="phone_desc text-left">$@Html.DisplayFor(model => model.Total) </h4>
                <div class="clearfix"> </div>
            </div>
        </div>
        <div class="clearfix"> </div>
    <br/>
    <p>
        @*@Html.ActionLink("Continue Shopping", "Index", "Index", "Items")*@
        <div class="col-md-1"></div>
        <div class="col-md-2 text-left">
            <a href="@Url.Action("Index", "Items", new {ItemId = Model.Id })" class="btn btn-primary btn-normal btn-inline btn_form button item_add item_1" target="_self">Continue Shopping</a>
        </div>    
    </p>
    </div>
        <div class="clearfix"> </div>
    </div>